version: '3.8'

services:
  web:
    image: vulnerables/web-dvwa
    ports:
      - "80:80" # Port lokal dihubungkan ke port 80 dalam container
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=app # Username MariaDB sesuai nama user
      - DB_PASSWORD=passwd # Password untuk user 'suguru'
      - DB_NAME=dvwa
    restart: always

  db:
    image: mariadb:latest # Menggunakan MariaDB versi 10.5
    environment:
      MYSQL_ROOT_PASSWORD: login0000 # Password untuk user root MariaDB
      MYSQL_DATABASE: dvwa # Nama database yang akan dibuat
      MYSQL_USER: suguru # Username MariaDB sesuai nama user
      MYSQL_PASSWORD: login # Password untuk user 'suguru'
    volumes:
      - db_data:/var/lib/mysql # Volume untuk menyimpan data MariaDB
    restart: always
        
volumes:
  db_data: # Volume untuk data MariaD
