version: '3.8'

services:
  web:
    image: vulnerables/web-dvwa
    ports:
      - "80:80" 
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=app 
      - DB_PASSWORD=passwd
      - DB_NAME=dvwa
    restart: always

  db:
    image: mariadb:latest 
    environment:
      MYSQL_ROOT_PASSWORD: login0000
      MYSQL_DATABASE: dvwa 
      MYSQL_USER: suguru 
      MYSQL_PASSWORD: login
    volumes:
      - db_data:/var/lib/mysql
    restart: always
        
volumes:
  db_data: 
